### ISSUE TITLE
I miss the old site :(

### ISSUE THREAD

**Issue by Natewich** [daneden/daneden.me#17]
I really enjoyed your previous website with the dope matrix3d transform, I'd love to hear about why you made the change. 

Keep up the good work.
- Nate

**Comment by daneden** [comment]
Hey Nate! Sorry I missed this issue until right now. In truth, my website is my sandbox, and as such is prone to frequent experimentation. The 3D-transformed iteration was one such experiment, and one that I really liked too, but I decided it was no longer reflective of my state of mind or approach to my work.

My site's home page has been through at least two iterations since, and I've liked each one for its own reasons. One day I'll undoubtedly make a return (if only brief) to more experimental approaches.

**Comment by Natewich** [comment]
Man, I totally get it.  I have sites and shit everywhere for all kinds of
reasons.  I only half meant the issue, as I know every iteration is another
blast of inspiration for myself.  Keep killing it dude.
